(function ()
{
    'use strict';

    angular
        .module('app.core',
            [
                'ngAnimate',
                'ngAria',
                'ngCookies',
                'ngMessages',
                'ngResource',
                'ngSanitize',
                'ngTouch',
                'ngMaterial',
                'angular-loading-bar',
                //'angular-chartist',
                //'chart.js',
                'trNgGrid',
                'datatables',
                //'gridshore.c3js.chart',
                //'nvd3',
                'pascalprecht.translate',
                'timer',
                'ui.router',
                'uiGmapgoogle-maps',
                'textAngular',
                'ng-sortable',
                'backTop',
                'ksSwiper',
                'ngLodash',
                'angularSoap',
                'angular-storage',
                'disableAll',
                'froala',
                'highcharts-ng',
                'ngPapaParse'
            ]);
})();
